<a href="https://colab.research.google.com/github/DillonZdrojewski/Week-4-/blob/main/week4_01_groupby.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercise: GroupBy
Alcohol Consumption Exercise

### Introduction:

Thanks to: https://github.com/justmarkham for the dataset and materials.

Import the necessary libraries

In [81]:
import numpy as np
import pandas as pd

[link text](https://)### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/drinks.csv), and assign it to a variable called drinks.

In [82]:
drinks = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/drinks.csv')
drinks.head(20)

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,AS
1,Albania,89,132,54,4.9,EU
2,Algeria,25,0,14,0.7,AF
3,Andorra,245,138,312,12.4,EU
4,Angola,217,57,45,5.9,AF
5,Antigua & Barbuda,102,128,45,4.9,NaN
6,Argentina,193,25,221,8.3,SA
7,Armenia,21,179,11,3.8,EU
8,Australia,261,72,212,10.4,OC
9,Austria,279,75,191,9.7,EU
10,Azerbaijan,21,46,5,1.3,EU
11,Bahamas,122,176,51,6.3,NaN
12,Bahrain,42,63,7,2.0,AS
13,Bangladesh,0,0,0,0.0,AS
14,Barbados,143,173,36,6.3,NaN
15,Belarus,142,373,42,14.4,EU
16,Belgium,295,84,212,10.5,EU
17,Belize,263,114,8,6.8,NaN
18,Benin,34,4,13,1.1,AF
19,Bhutan,23,0,0,0.4,AS

### What is the number of observations in the dataset?

In [83]:
drinks.info()
drinks.shape[0]
drinks.shape[1]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 193 entries, 0 to 192
Data columns (total 6 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   country                       193 non-null    object
 1   beer_servings                 193 non-null    int64
 2   spirit_servings               193 non-null    int64
 3   wine_servings                 193 non-null    int64
 4   total_litres_of_pure_alcohol  193 non-null    float64
 5   continent                     170 non-null    object
dtypes: float64(1), int64(3), object(2)
memory usage: 9.2+ KB

6

### Show me the names of all columns, and how the dataset is indexed.

In [84]:
print('The column names are:',drinks.columns)
print('\n\nThe index:',drinks.index)

The column names are: Index(['country', 'beer_servings', 'spirit_servings', 'wine_servings',
       'total_litres_of_pure_alcohol', 'continent'],
      dtype='object')


The index: RangeIndex(start=0, stop=193, step=1)

## How many continents are there?

In [85]:
drinks.continent.unique()
drinks.continent.nunique()

5

In [86]:
drinks.continent.value_counts().head()

continent
AF    53
EU    45
AS    44
OC    16
SA    12
Name: count, dtype: int64

### How much beer does the world drink on average?

In [87]:
drinks['beer_servings'].mean()
drinks.beer_servings.mean()

106.16062176165804

### Class Exercise: How much spirit does the world drink in total? Hint: SUM

In [88]:
## Enter your answer here:
drinks['spirit_servings'].sum()

15632

### Which country drinks the highest servings of wine?

Steps: Find the index location where wine_serving is highest. Next, locate the name of the country attached to this high wine consumption.

In [89]:
print('highest servings of wine is located at row:',drinks['wine_servings'].idxmax())

print('\nThe country that drinks the highest amount of wine is:',drinks['country'][drinks['wine_servings'].idxmax()])

print('\nThe other features of France:\n',drinks.loc[drinks['wine_servings'].idxmax()])

highest servings of wine is located at row: 61

The country that drinks the highest amount of wine is: France

The other features of France:
 country                         France
beer_servings                      127
spirit_servings                    151
wine_servings                      370
total_litres_of_pure_alcohol      11.8
continent                           EU
Name: 61, dtype: object

In [90]:
drinks['wine_servings'].idxmax()

drinks['country'][drinks['wine_servings'].idxmax()]

'France'

In [91]:
## Alternatively, sort drinks by highest wine servings
drinks.sort_values(by='wine_servings',ascending=False).head()

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
61,France,127,151,370,11.8,EU
136,Portugal,194,67,339,11.0,EU
3,Andorra,245,138,312,12.4,EU
166,Switzerland,185,100,280,10.2,EU
48,Denmark,224,81,278,10.4,EU

## Class Exercise: How much servings of wine is had by the country that drinks the most servings of spirit? Which country is it?

In [92]:
drinks['spirit_servings'].idxmax()
drinks.loc[drinks['spirit_servings'].idxmax()]

country                         Grenada
beer_servings                       199
spirit_servings                     438
wine_servings                        28
total_litres_of_pure_alcohol       11.9
continent                           NaN
Name: 68, dtype: object


## We will now start grouping by a category to answer more complicated questions.

#### Which continent drinks the most beer on average? To answer this, we will GROUPBY continent and then find the average.

In [93]:
 drinks.beer_servings.mean()

drinks.groupby('continent').beer_servings.mean()

continent
AF     61.471698
AS     37.045455
EU    193.777778
OC     89.687500
SA    175.083333
Name: beer_servings, dtype: float64

In [94]:
print('The continent that drinks the most beer:',drinks.groupby('continent').beer_servings.mean().idxmax())

drinks.groupby('continent').beer_servings.mean().sort_values(ascending=False)

The continent that drinks the most beer: EU

continent
EU    193.777778
SA    175.083333
OC     89.687500
AF     61.471698
AS     37.045455
Name: beer_servings, dtype: float64

## Class Exercise: Print the summary statistics for wine consumption for each continent.

In [95]:
## Enter your answer here
summary = drinks.groupby('continent').wine_servings.describe()
summary

           count        mean        std  min   25%    50%     75%    max
continent
AF          53.0   16.264151  38.846419  0.0   1.0    2.0   13.00  233.0
AS          44.0    9.068182  21.667034  0.0   0.0    1.0    8.00  123.0
EU          45.0  142.222222  97.421738  0.0  59.0  128.0  195.00  370.0
OC          16.0   35.625000  64.555790  0.0   1.0    8.5   23.25  212.0
SA          12.0   62.416667  88.620189  1.0   3.0   12.0   98.50  221.0

### Print the mean alcohol consumption per continent for every type of alcohol

In [96]:
drinks.groupby('continent')['wine_servings'].mean()

continent
AF     16.264151
AS      9.068182
EU    142.222222
OC     35.625000
SA     62.416667
Name: wine_servings, dtype: float64

### Class Exercise: Print the median alcohol consumption per continent for every column

In [97]:
## Enter your answer here
drinks.groupby('continent')[['wine_servings', 'beer_servings','spirit_servings']].median()

           wine_servings  beer_servings  spirit_servings
continent
AF                   2.0           32.0              3.0
AS                   1.0           17.5             16.0
EU                 128.0          219.0            122.0
OC                   8.5           52.5             37.0
SA                  12.0          162.5            108.5

### Print the mean, min and max values for spirit consumption.

In [98]:
drinks.groupby('continent').spirit_servings.agg(['mean', 'min', 'max'])

                 mean  min  max
continent
AF          16.339623    0  152
AS          60.840909    0  326
EU         132.555556    0  373
OC          58.437500    0  254
SA         114.750000   25  302

In [99]:
# reset index to continent and set it back to how it was previously
drinks

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,AS
1,Albania,89,132,54,4.9,EU
2,Algeria,25,0,14,0.7,AF
3,Andorra,245,138,312,12.4,EU
4,Angola,217,57,45,5.9,AF
...,...,...,...,...,...,...
188,Venezuela,333,100,3,7.7,SA
189,Vietnam,111,2,1,2.0,AS
190,Yemen,6,0,0,0.1,AS
191,Zambia,32,19,4,2.5,AF
192,Zimbabwe,64,18,4,4.7,AF

In [101]:
drinks1 = drinks.set_index('continent')
drinks1.head()

#reset index of drinks
drinks1 = drinks1.reset_index()
drinks1.head()

,continent,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
0,AS,Afghanistan,0,0,0,0.0
1,EU,Albania,89,132,54,4.9
2,AF,Algeria,25,0,14,0.7
3,EU,Andorra,245,138,312,12.4
4,AF,Angola,217,57,45,5.9